server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms_category?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    locations: classpath:db/migration
    validate-on-migrate: false
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 1
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

logging:
  level:
    org.flywaydb: DEBUG
