server:
  port: 8070

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderservice?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

application:
  config:
    customer-url: http://localhost:8090/api/v1/customers
    payment-url: http://localhost:8060/api/v1/payments
    product-url: http://localhost:8050/api/v1/products
