server:
  port: 8060
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paymentservice?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

application:
  config:
    customer-url: http://localhost:8090/api/v1/customers

