server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms_user?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: likhithap012@gmail.com
    password: msze sknv yxhx zpdy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  jwt:
    secret: bXktc3VwZXItc2VjdXJlLWp3dC1zZWNyZXQtMjAyNS1rZXkh
    expiration: 1
